package com.umbra.app.domain.nip77

import com.umbra.app.domain.util.toHex
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * End-to-end reconciliation conformance tests. Every expected message byte sequence and
 * have/need id set below was generated by actually running the reference JS implementation
 * (github.com/hoytech/negentropy, js/Negentropy.js) against the exact same input items, not
 * re-derived from this Kotlin port's own logic — this is what catches a self-consistent but
 * spec-incorrect port, which a test suite written purely from this file's own understanding of
 * the algorithm never could.
 */
class NegentropyReconcilerConformanceTest {

    private fun fakeId(i: Int): String = i.toString(16).padStart(4, '0').repeat(16)

    private fun runReconciliation(
        clientItems: List<Pair<Long, String>>,
        serverItems: List<Pair<Long, String>>
    ): Triple<List<Pair<String, String?>>, List<String>, List<String>> {
        val client = NegentropyReconciler(
            NegentropyStorageVector(clientItems.map { NegentropyItem(it.second, it.first) }),
            isInitiator = true
        )
        val server = NegentropyReconciler(
            NegentropyStorageVector(serverItems.map { NegentropyItem(it.second, it.first) }),
            isInitiator = false
        )

        val messages = mutableListOf<Pair<String, String?>>()
        val haveIds = mutableListOf<String>()
        val needIds = mutableListOf<String>()

        var msg: ByteArray? = client.initiate()
        messages.add("client" to msg!!.toHex())
        var serverTurn = true
        var rounds = 0
        while (msg != null && rounds < 50) {
            rounds++
            if (serverTurn) {
                val result = server.reconcile(msg)
                messages.add("server" to result.outgoingMessage?.toHex())
                msg = result.outgoingMessage
            } else {
                val result = client.reconcile(msg)
                haveIds.addAll(result.haveIds)
                needIds.addAll(result.needIds)
                messages.add("client" to result.outgoingMessage?.toHex())
                msg = result.outgoingMessage
            }
            serverTurn = !serverTurn
        }

        return Triple(messages, haveIds.sorted(), needIds.sorted())
    }

    @Test
    fun `given identical when reconciling then matches reference implementation exactly`() {
        val clientItems: List<Pair<Long, String>> = listOf(
            1000L to fakeId(1),
            1001L to fakeId(2),
            1002L to fakeId(3)
        )
        val serverItems: List<Pair<Long, String>> = listOf(
            1000L to fakeId(1),
            1001L to fakeId(2),
            1002L to fakeId(3)
        )

        val (messages, haveIds, needIds) = runReconciliation(clientItems, serverItems)

        assertEquals(
            listOf(
            "client" to "6100000203000100010001000100010001000100010001000100010001000100010001000100020002000200020002000200020002000200020002000200020002000200020003000300030003000300030003000300030003000300030003000300030003",
            "server" to "6100000203000100010001000100010001000100010001000100010001000100010001000100020002000200020002000200020002000200020002000200020002000200020003000300030003000300030003000300030003000300030003000300030003",
            "client" to null
        ),
            messages
        )
        assertEquals(emptyList<String>(), haveIds)
        assertEquals(emptyList<String>(), needIds)
    }

    @Test
    fun `given client has extra when reconciling then matches reference implementation exactly`() {
        val clientItems: List<Pair<Long, String>> = listOf(
            1000L to fakeId(1),
            1001L to fakeId(2),
            1002L to fakeId(3)
        )
        val serverItems: List<Pair<Long, String>> = listOf(
            1000L to fakeId(1),
            1001L to fakeId(2)
        )

        val (messages, haveIds, needIds) = runReconciliation(clientItems, serverItems)

        assertEquals(
            listOf(
            "client" to "6100000203000100010001000100010001000100010001000100010001000100010001000100020002000200020002000200020002000200020002000200020002000200020003000300030003000300030003000300030003000300030003000300030003",
            "server" to "610000020200010001000100010001000100010001000100010001000100010001000100010002000200020002000200020002000200020002000200020002000200020002",
            "client" to null
        ),
            messages
        )
        assertEquals(listOf(
            "0003000300030003000300030003000300030003000300030003000300030003"
        ), haveIds)
        assertEquals(emptyList<String>(), needIds)
    }

    @Test
    fun `given server has extra when reconciling then matches reference implementation exactly`() {
        val clientItems: List<Pair<Long, String>> = listOf(
            1000L to fakeId(1),
            1001L to fakeId(2)
        )
        val serverItems: List<Pair<Long, String>> = listOf(
            1000L to fakeId(1),
            1001L to fakeId(2),
            1002L to fakeId(3)
        )

        val (messages, haveIds, needIds) = runReconciliation(clientItems, serverItems)

        assertEquals(
            listOf(
            "client" to "610000020200010001000100010001000100010001000100010001000100010001000100010002000200020002000200020002000200020002000200020002000200020002",
            "server" to "6100000203000100010001000100010001000100010001000100010001000100010001000100020002000200020002000200020002000200020002000200020002000200020003000300030003000300030003000300030003000300030003000300030003",
            "client" to null
        ),
            messages
        )
        assertEquals(emptyList<String>(), haveIds)
        assertEquals(listOf(
            "0003000300030003000300030003000300030003000300030003000300030003"
        ), needIds)
    }

    @Test
    fun `given both empty when reconciling then matches reference implementation exactly`() {
        val clientItems: List<Pair<Long, String>> = emptyList<Pair<Long, String>>()
        val serverItems: List<Pair<Long, String>> = emptyList<Pair<Long, String>>()

        val (messages, haveIds, needIds) = runReconciliation(clientItems, serverItems)

        assertEquals(
            listOf(
            "client" to "6100000200",
            "server" to "6100000200",
            "client" to null
        ),
            messages
        )
        assertEquals(emptyList<String>(), haveIds)
        assertEquals(emptyList<String>(), needIds)
    }

    @Test
    fun `given client empty when reconciling then matches reference implementation exactly`() {
        val clientItems: List<Pair<Long, String>> = emptyList<Pair<Long, String>>()
        val serverItems: List<Pair<Long, String>> = listOf(
            1000L to fakeId(1),
            1001L to fakeId(2)
        )

        val (messages, haveIds, needIds) = runReconciliation(clientItems, serverItems)

        assertEquals(
            listOf(
            "client" to "6100000200",
            "server" to "610000020200010001000100010001000100010001000100010001000100010001000100010002000200020002000200020002000200020002000200020002000200020002",
            "client" to null
        ),
            messages
        )
        assertEquals(emptyList<String>(), haveIds)
        assertEquals(listOf(
            "0001000100010001000100010001000100010001000100010001000100010001",
            "0002000200020002000200020002000200020002000200020002000200020002"
        ), needIds)
    }

    @Test
    fun `given large disjoint when reconciling then matches reference implementation exactly`() {
        val clientItems: List<Pair<Long, String>> = listOf(
            1000L to fakeId(0),
            1001L to fakeId(1),
            1002L to fakeId(2),
            1003L to fakeId(3),
            1004L to fakeId(4),
            1005L to fakeId(5),
            1006L to fakeId(6),
            1007L to fakeId(7),
            1008L to fakeId(8),
            1009L to fakeId(9),
            1010L to fakeId(10),
            1011L to fakeId(11),
            1012L to fakeId(12),
            1013L to fakeId(13),
            1014L to fakeId(14),
            1015L to fakeId(15),
            1016L to fakeId(16),
            1017L to fakeId(17),
            1018L to fakeId(18),
            1019L to fakeId(19),
            1020L to fakeId(20),
            1021L to fakeId(21),
            1022L to fakeId(22),
            1023L to fakeId(23),
            1024L to fakeId(24),
            1025L to fakeId(25),
            1026L to fakeId(26),
            1027L to fakeId(27),
            1028L to fakeId(28),
            1029L to fakeId(29),
            1030L to fakeId(30),
            1031L to fakeId(31),
            1032L to fakeId(32),
            1033L to fakeId(33),
            1034L to fakeId(34),
            1035L to fakeId(35),
            1036L to fakeId(36),
            1037L to fakeId(37),
            1038L to fakeId(38),
            1039L to fakeId(39)
        )
        val serverItems: List<Pair<Long, String>> = listOf(
            1020L to fakeId(20),
            1021L to fakeId(21),
            1022L to fakeId(22),
            1023L to fakeId(23),
            1024L to fakeId(24),
            1025L to fakeId(25),
            1026L to fakeId(26),
            1027L to fakeId(27),
            1028L to fakeId(28),
            1029L to fakeId(29),
            1030L to fakeId(30),
            1031L to fakeId(31),
            1032L to fakeId(32),
            1033L to fakeId(33),
            1034L to fakeId(34),
            1035L to fakeId(35),
            1036L to fakeId(36),
            1037L to fakeId(37),
            1038L to fakeId(38),
            1039L to fakeId(39),
            1040L to fakeId(40),
            1041L to fakeId(41),
            1042L to fakeId(42),
            1043L to fakeId(43),
            1044L to fakeId(44),
            1045L to fakeId(45),
            1046L to fakeId(46),
            1047L to fakeId(47),
            1048L to fakeId(48),
            1049L to fakeId(49),
            1050L to fakeId(50),
            1051L to fakeId(51),
            1052L to fakeId(52),
            1053L to fakeId(53),
            1054L to fakeId(54),
            1055L to fakeId(55),
            1056L to fakeId(56),
            1057L to fakeId(57),
            1058L to fakeId(58),
            1059L to fakeId(59)
        )

        val (messages, haveIds, needIds) = runReconciliation(clientItems, serverItems)

        assertEquals(
            listOf(
            "client" to "61876c0001381174f509f23b4c36dc113e1b2acfeb0400017a212ff12dbac77caf41408354b31dde0400011e58c0043e7aa755ec266bc02ea0eb47040001bded42097e08e77728332c3f0abb132d0400017e8ff97a2b314c2e02c0640cf876797c040001e7a43afc2d7550e25d78c774b26075ad04000194e73a1c408953a5a32872e6ffe6bc050400017fa38309afb639f7ee5dc4dcad6ab3d7030001fe67aa48bf776130fc082911c28b7eed0300014f3347a2894aec66ce9dceb4d80ccb28030001dfae5a0c128d02eb997215cf68734f2c0300019326ef10d7330637a27a5f198726e0b20300011241147e1176808ddcabec23790b3dce030001375034a54874dcd2d2d6550f49908a9e030001a6898987cfe8b09ff55533d5d5651d2d000001e697293e6ff3f85b8df011578a5ec451",
            "server" to "61876c0002000400020004000200040002000400020004000200040002010014001400140014001400140014001400140014001400140014001400140014120000000002160026002600260026002600260026002600260026002600260026002600260026002700270027002700270027002700270027002700270027002700270027002700280028002800280028002800280028002800280028002800280028002800280029002900290029002900290029002900290029002900290029002900290029002a002a002a002a002a002a002a002a002a002a002a002a002a002a002a002a002b002b002b002b002b002b002b002b002b002b002b002b002b002b002b002b002c002c002c002c002c002c002c002c002c002c002c002c002c002c002c002c002d002d002d002d002d002d002d002d002d002d002d002d002d002d002d002d002e002e002e002e002e002e002e002e002e002e002e002e002e002e002e002e002f002f002f002f002f002f002f002f002f002f002f002f002f002f002f002f0030003000300030003000300030003000300030003000300030003000300030003100310031003100310031003100310031003100310031003100310031003100320032003200320032003200320032003200320032003200320032003200320033003300330033003300330033003300330033003300330033003300330033003400340034003400340034003400340034003400340034003400340034003400350035003500350035003500350035003500350035003500350035003500350036003600360036003600360036003600360036003600360036003600360036003700370037003700370037003700370037003700370037003700370037003700380038003800380038003800380038003800380038003800380038003800380039003900390039003900390039003900390039003900390039003900390039003a003a003a003a003a003a003a003a003a003a003a003a003a003a003a003a003b003b003b003b003b003b003b003b003b003b003b003b003b003b003b003b",
            "client" to null
        ),
            messages
        )
        assertEquals(listOf(
            "0000000000000000000000000000000000000000000000000000000000000000",
            "0001000100010001000100010001000100010001000100010001000100010001",
            "0002000200020002000200020002000200020002000200020002000200020002",
            "0003000300030003000300030003000300030003000300030003000300030003",
            "0004000400040004000400040004000400040004000400040004000400040004",
            "0005000500050005000500050005000500050005000500050005000500050005",
            "0006000600060006000600060006000600060006000600060006000600060006",
            "0007000700070007000700070007000700070007000700070007000700070007",
            "0008000800080008000800080008000800080008000800080008000800080008",
            "0009000900090009000900090009000900090009000900090009000900090009",
            "000a000a000a000a000a000a000a000a000a000a000a000a000a000a000a000a",
            "000b000b000b000b000b000b000b000b000b000b000b000b000b000b000b000b",
            "000c000c000c000c000c000c000c000c000c000c000c000c000c000c000c000c",
            "000d000d000d000d000d000d000d000d000d000d000d000d000d000d000d000d",
            "000e000e000e000e000e000e000e000e000e000e000e000e000e000e000e000e",
            "000f000f000f000f000f000f000f000f000f000f000f000f000f000f000f000f",
            "0010001000100010001000100010001000100010001000100010001000100010",
            "0011001100110011001100110011001100110011001100110011001100110011",
            "0012001200120012001200120012001200120012001200120012001200120012",
            "0013001300130013001300130013001300130013001300130013001300130013"
        ), haveIds)
        assertEquals(listOf(
            "0028002800280028002800280028002800280028002800280028002800280028",
            "0029002900290029002900290029002900290029002900290029002900290029",
            "002a002a002a002a002a002a002a002a002a002a002a002a002a002a002a002a",
            "002b002b002b002b002b002b002b002b002b002b002b002b002b002b002b002b",
            "002c002c002c002c002c002c002c002c002c002c002c002c002c002c002c002c",
            "002d002d002d002d002d002d002d002d002d002d002d002d002d002d002d002d",
            "002e002e002e002e002e002e002e002e002e002e002e002e002e002e002e002e",
            "002f002f002f002f002f002f002f002f002f002f002f002f002f002f002f002f",
            "0030003000300030003000300030003000300030003000300030003000300030",
            "0031003100310031003100310031003100310031003100310031003100310031",
            "0032003200320032003200320032003200320032003200320032003200320032",
            "0033003300330033003300330033003300330033003300330033003300330033",
            "0034003400340034003400340034003400340034003400340034003400340034",
            "0035003500350035003500350035003500350035003500350035003500350035",
            "0036003600360036003600360036003600360036003600360036003600360036",
            "0037003700370037003700370037003700370037003700370037003700370037",
            "0038003800380038003800380038003800380038003800380038003800380038",
            "0039003900390039003900390039003900390039003900390039003900390039",
            "003a003a003a003a003a003a003a003a003a003a003a003a003a003a003a003a",
            "003b003b003b003b003b003b003b003b003b003b003b003b003b003b003b003b"
        ), needIds)
    }

}
