package com.umbra.app.domain.nip77

import com.umbra.app.domain.util.toHex
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Ground-truth fingerprints generated by running the reference JS implementation
 * (github.com/hoytech/negentropy, js/Negentropy.js) directly — not re-derived from this port's
 * own logic — so a mistaken understanding of the spec can't produce a self-consistent but
 * wrong-versus-reality implementation.
 */
class NegentropyFingerprintTest {

    @Test
    fun `given no ids when computing fingerprint then matches reference implementation`() {
        val fp = NegentropyFingerprint.compute(emptyList())
        assertEquals("7f9c9e31ac8256ca2f258583df262dbc", fp.toHex())
    }

    @Test
    fun `given a single all-zero id when computing fingerprint then matches reference implementation`() {
        val fp = NegentropyFingerprint.compute(listOf("00".repeat(32)))
        assertEquals("1fd4247443c9440cb3c48c2885193719", fp.toHex())
    }

    @Test
    fun `given a single all-ff id when computing fingerprint then matches reference implementation`() {
        val fp = NegentropyFingerprint.compute(listOf("ff".repeat(32)))
        assertEquals("8f04045cb5b643a45a2df62d82153528", fp.toHex())
    }

    @Test
    fun `given three ids when computing fingerprint then matches reference implementation`() {
        val ids = listOf(
            "0001".repeat(16),
            "0002".repeat(16),
            "0003".repeat(16)
        )
        val fp = NegentropyFingerprint.compute(ids)
        assertEquals("c47d8f35bd55c9c881031ec332e251d9", fp.toHex())
    }

    @Test
    fun `given the same ids in a different order when computing fingerprint then result is unchanged`() {
        val ids = listOf("0001".repeat(16), "0002".repeat(16), "0003".repeat(16))
        val forward = NegentropyFingerprint.compute(ids)
        val reversed = NegentropyFingerprint.compute(ids.reversed())
        assertEquals(forward.toHex(), reversed.toHex())
    }
}
